mybatis-plus:
  mapper-locations: classpath:/mapper/**/**.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: del_flag
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    id-type: 3