spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      master:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://winemall.master.dbsmzc.yw.vvip-u.com:3306/smcx_winemall_order?autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: smapp
        password: smcdyanfa
        initialSize: 2
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
      slave:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://winemall.slaver.dbsmzc.yw.vvip-u.com:3306/smcx_winemall_order?autoReconnectForPools=true&useUnicode=true&characterEncoding=utf8&useSSL=false
        username: smapp
        password: smcdyanfa
        initialSize: 2
        minIdle: 5
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        useGlobalDataSourceStat: true
